# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 FernTech

[package]
name = "scene-corkboard"
edition = "2024"
version.workspace = true
authors.workspace = true
publish = false

[dependencies]
teksilo = { workspace = true, features = ["automation"] }
teksilo-scene = { workspace = true }
accesskit = { workspace = true }
