[package]
name = "fern-canvas"
edition = "2024"
version.workspace = true
license-file.workspace = true
publish.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
fern-tokens = { workspace = true }
roxmltree = { workspace = true }
png = { workspace = true }
image-webp = { workspace = true }
thiserror = { workspace = true }
