[package]
name = "telemetry-fern"
edition = "2024"
version.workspace = true
license-file.workspace = true
authors.workspace = true
publish = false

[dependencies]
fern-ui = { workspace = true, features = ["telemetry"] }
fern-analytics-fern = { workspace = true }
fern-settings = { workspace = true }
fern-telemetry = { workspace = true }
fern-core = { workspace = true }
uuid = { workspace = true }
