//! The [`SceneItem`] trait and its supporting context types.
//!
//! Lightweight items live in a [`Scene`](crate::Scene) without arena
//! overhead. Each carries its own bounds (in **local item coordinates**,
//! origin at the item's anchor) and paints itself via
//! [`SceneView`](crate::SceneView)'s paint walk. Apps implement this
//! trait directly for custom items; built-ins live in
//! [`crate::items`].
//!
//! # Coordinate model
//!
//! An item is positioned in its parent's coordinate space by a
//! `local_pos: Point` plus an optional `transform: Transform2D`
//! (rotation/scale, applied around the local origin). The Scene
//! composes those per-item transforms up the parent chain to produce
//! a `scene_transform` (local→scene). Hit-test inverse-transforms a
//! scene-coord point into local coords before calling
//! [`SceneItem::shape_contains`]; paint pushes the scene transform
//! onto the canvas before calling [`SceneItem::paint`].

use accesskit::Role;
use fern_canvas::{Canvas, Point, Rect, Transform2D};
use fern_core::accessibility::AccessNodeBuilder;
use fern_core::build_context::BuildContext;
use fern_core::widget_id::WidgetId;

use crate::flags::ItemFlags;

/// Opaque identifier for a [`SceneItem`] inside a [`Scene`](crate::Scene).
///
/// Globally unique within a process, generated by [`ItemId::next`].
/// `ItemId`s are stable across the item's lifetime in a scene; removing
/// an item retires its id permanently (`Scene::remove` does not reuse).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ItemId(pub(crate) u64);

impl ItemId {
    /// Mint a fresh globally-unique id. Used internally by Scene.
    pub(crate) fn next() -> Self {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(1);
        Self(COUNTER.fetch_add(1, Ordering::Relaxed))
    }

    /// Raw numeric value, used by AccessKit's synthetic-NodeId derivation.
    pub fn as_u64(self) -> u64 {
        self.0
    }
}

/// Context handed to [`SceneItem::paint`].
///
/// `view_transform` is the composed pan/zoom/rotation of the SceneView
/// that's painting this item; the canvas already has the item's
/// `scene_transform` pushed, so paint methods work in local coords
/// without further matrix math.
pub struct SceneItemPaintContext {
    /// View pan/zoom/rotation as a single affine. Items rarely need
    /// this directly — the canvas's transform stack already accounts
    /// for it — but custom items wanting to draw at a fixed pixel
    /// size regardless of zoom can read the zoom factor from here.
    pub view_transform: Transform2D,
    /// Optional scene-coord region the renderer is currently
    /// repainting. Items that internally subdivide their geometry
    /// can use this to skip work outside the dirty region. `None`
    /// means "full repaint".
    pub dirty_scene_rect: Option<Rect>,
}

impl SceneItemPaintContext {
    /// Construct a paint context with the given view transform and
    /// optional dirty region.
    pub fn new(view_transform: Transform2D, dirty_scene_rect: Option<Rect>) -> Self {
        Self {
            view_transform,
            dirty_scene_rect,
        }
    }
}

/// Context handed to [`SceneItem::accessibility`].
///
/// Carries the item's screen-projected bounds (so items wanting to
/// emit AT-relative coordinates can read them) and its `ItemId` so
/// implementations can derive synthetic AT NodeIds for sub-elements.
pub struct SceneItemA11yContext {
    /// View transform (pan/zoom/rotation) at AT-build time.
    pub view_transform: Transform2D,
    /// Item's bounds projected into screen space.
    pub screen_bounds: Rect,
    /// The id under which this item is being emitted.
    pub item_id: ItemId,
}

/// A lightweight, paint-only scene-graph item.
///
/// Implementations carry their own bounds (in local coords, anchored
/// at the origin) and provide a `paint` method that draws into a
/// [`Canvas`]. The Scene takes care of positioning, transform-chain
/// composition, hit-test, accessibility, and repaint scheduling.
///
/// # Required methods
///
/// * [`SceneItem::local_bounds`] — AABB in local item coords.
/// * [`SceneItem::set_local_bounds`] — write back the bounds field
///   when the Scene mutates it.
/// * [`SceneItem::paint`] — draw the item into the canvas. The canvas
///   already has the item's `scene_transform` pushed, so coordinates
///   are in local item space.
///
/// # Optional methods
///
/// * [`SceneItem::shape_contains`] — exact-shape hit-test in local
///   coords. Default is AABB containment.
/// * [`SceneItem::label`] — human-readable label for AT and debug.
/// * [`SceneItem::register_bindings`] — bind reactive signals to the
///   SceneView's repaint machinery.
/// * [`SceneItem::accessibility`] — populate the AccessKit node.
pub trait SceneItem: std::fmt::Debug + 'static {
    /// AABB in **local item coordinates** (origin at the item's
    /// anchor). The Scene composes this with the item's
    /// `scene_transform` to compute its scene-space AABB for the
    /// spatial index.
    fn local_bounds(&self) -> Rect;

    /// Write back new bounds. Called by [`Scene::set_local_bounds`]
    /// when the bounds change. Implementations update their stored
    /// bounds field; geometry-bearing items (e.g. [`crate::PathItem`])
    /// must keep their geometry consistent with the new bounds.
    fn set_local_bounds(&mut self, bounds: Rect);

    /// Paint the item into the canvas. The canvas already has this
    /// item's `scene_transform` (parent chain × view) pushed, so
    /// coordinates are in **local** item space — `(0, 0)` is the
    /// item's anchor.
    fn paint(&self, canvas: &mut Canvas, ctx: &SceneItemPaintContext);

    /// Exact-shape hit-test in **local** coordinates. Default: AABB
    /// containment via [`SceneItem::local_bounds`]. Path-based items
    /// override this to do per-segment distance checks so users can
    /// click along a stroke even when the AABB is huge.
    fn shape_contains(&self, local_pt: Point) -> bool {
        self.local_bounds().contains(local_pt)
    }

    /// The flags this item should carry into the Scene at insert
    /// time. Default: `ItemFlags::default()` — visible, enabled,
    /// selectable. Built-ins read their accumulated builder state
    /// (e.g. `.draggable(true)` flips `IS_DRAGGABLE`); custom items
    /// override this to opt into hover acceptance, focus, clipping,
    /// or `IGNORES_TRANSFORMATIONS`.
    ///
    /// Read once by [`Scene::add_item`](crate::Scene::add_item) and
    /// stored on the entry. Subsequent flag changes go through
    /// [`Scene::set_flag`](crate::Scene::set_flag) /
    /// [`Scene::set_flags`](crate::Scene::set_flags).
    fn initial_flags(&self) -> ItemFlags {
        ItemFlags::default()
    }

    /// Optional human-readable label, surfaced in debug introspection
    /// and used by the default [`SceneItem::accessibility`] impl as
    /// the AT name when an item author hasn't overridden it via the
    /// per-item `.access_label(...)` chain.
    fn label(&self) -> Option<String> {
        None
    }

    /// Register reactive bindings the item depends on. Called once
    /// per [`SceneView::build`](crate::SceneView) for every item in
    /// the scene, with the SceneView's `WidgetId` as `view_id`. Items
    /// with signal-bound state bind their signals here at the
    /// appropriate [`BindingLevel`](fern_core::binding::BindingLevel).
    fn register_bindings(&self, _ctx: &mut BuildContext, _view_id: WidgetId) {}

    /// Populate the AccessKit node for this item. Default: role
    /// [`Role::GraphicsObject`] plus the [`SceneItem::label`] as the
    /// AT name if set. The per-item `.access_*` builder chain layers
    /// overrides on top of whatever this method writes.
    fn accessibility(&self, builder: &mut AccessNodeBuilder, _ctx: &SceneItemA11yContext) {
        builder.set_role(Role::GraphicsObject);
        if let Some(label) = self.label() {
            builder.set_name(label);
        }
    }
}
