# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 FernTech

[package]
name = "telemetry-plausible"
edition = "2024"
version.workspace = true
license-file.workspace = true
authors.workspace = true
publish = false

[dependencies]
bastyde = { workspace = true, features = [
    "automation","telemetry"] }
bastyde-analytics-plausible = { workspace = true }
bastyde-settings = { workspace = true }
bastyde-telemetry = { workspace = true }
bastyde-core = { workspace = true }
