# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 FernTech

[package]
name = "datetime-pickers"
edition = "2024"
version.workspace = true
license-file.workspace = true
authors.workspace = true
publish = false

[dependencies]
bastyde = { workspace = true }
jiff = { workspace = true }
