// SPDX-License-Identifier: MPL-2.0
// SPDX-FileCopyrightText: 2026 FernTech

//! The WinUI 3 theme-resource palette, attached to the theme as a typed
//! extension.
//!
//! Teksilo's [`ColorTokens`](teksilo_tokens::ColorTokens) carries one
//! semantic slot per *role*; Fluent's theme dictionary carries several
//! graded values per role (a control fill has Default / Secondary /
//! Tertiary / Disabled, a stroke has Default / Secondary / OnAccent*, …).
//! [`FluentPalette`] holds the full set so Fluent-aware app code and the
//! Fluent widget styles in this crate can read the exact token they need:
//!
//! ```ignore
//! if let Some(f) = theme.extension::<FluentPalette>() {
//!     let edge = f.control_stroke_secondary;
//! }
//! ```
//!
//! ## Provenance
//!
//! Every value below is transcribed from the `"Light"` / `"Default"`
//! (= Dark) `ResourceDictionary` entries of WinUI's
//! `Common_themeresources_any.xaml`, written in WinUI's own
//! `#AARRGGBB` notation via [`argb`] so a reviewer can diff them against
//! the XAML byte-for-byte.
//!
//! Two families are **not** static literals in that file and are resolved
//! here against the Windows out-of-box accent `#0078D4`:
//!
//! - `AccentFillColor*` / `AccentTextFillColor*` are
//!   `{ThemeResource SystemAccentColorDark1/2/3}` (light) and
//!   `SystemAccentColorLight1/2/3` (dark) bindings — the OS substitutes the
//!   user's accent at runtime.
//! - The accent ramp itself (`SystemAccentColorLight1..3` /
//!   `Dark1..3`) is generated by Windows from the base accent; Microsoft
//!   documents the mechanism but publishes no formula. The six ramp
//!   constants here are the values Windows 11 computes for the default
//!   `#0078D4`.
//!
//! [`FluentAccentRamp::from_base`] regenerates the ramp for a different
//! base accent, so an app that reads the user's Windows accent (or wants
//! a brand accent) can rebuild the whole theme around it — see
//! [`crate::light_with_accent`].

use teksilo_tokens::Color;

/// Decode a WinUI `#AARRGGBB` colour literal (or an opaque `#RRGGBB`).
///
/// WinUI's XAML writes alpha **first**; [`Color::from_hex`] expects it
/// last. Rather than reorder every literal by hand (and lose the ability
/// to diff this file against the theme dictionary), the WinUI order is
/// kept verbatim and decoded here.
pub fn argb(hex: &str) -> Color {
    let hex = hex.strip_prefix('#').unwrap_or(hex);
    let byte = |s: &str| -> f32 { u8::from_str_radix(s, 16).unwrap_or(0) as f32 / 255.0 };
    match hex.len() {
        8 => Color::new(
            byte(&hex[2..4]),
            byte(&hex[4..6]),
            byte(&hex[6..8]),
            byte(&hex[0..2]),
        ),
        6 => Color::new(byte(&hex[0..2]), byte(&hex[2..4]), byte(&hex[4..6]), 1.0),
        _ => Color::BLACK,
    }
}

/// Composite `top` over `bottom` (source-over), returning an opaque colour.
///
/// Most Fluent fills are translucent by design — they are meant to sit on
/// a known base layer. Teksilo slots that must hold an *opaque* value (a
/// window background, an editor surface) get the pre-composited result;
/// slots where the translucency is the point (strokes, hover washes,
/// scrims) keep their alpha.
pub fn over(top: Color, bottom: Color) -> Color {
    bottom.mix(Color::new(top.r(), top.g(), top.b(), bottom.a()), top.a())
}

/// The six shades Windows derives from a base accent colour, plus the base.
///
/// Windows generates these by walking the base accent's lightness in HSL;
/// the exact curve is unpublished, so [`FluentAccentRamp::windows_default`]
/// carries the values Windows 11 produces for its own default `#0078D4`
/// and [`FluentAccentRamp::from_base`] reproduces the curve closely enough
/// for a custom accent to read as Fluent.
///
/// Fluent uses the ramp **asymmetrically**: the light theme fills controls
/// with `dark1` (a darkened accent, so white label text clears contrast),
/// the dark theme fills them with `light2`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct FluentAccentRamp {
    pub dark3: Color,
    pub dark2: Color,
    pub dark1: Color,
    pub base: Color,
    pub light1: Color,
    pub light2: Color,
    pub light3: Color,
}

impl FluentAccentRamp {
    /// The ramp Windows 11 computes for its out-of-box accent `#0078D4`.
    pub fn windows_default() -> Self {
        Self {
            dark3: argb("#001A68"),
            dark2: argb("#003E92"),
            dark1: argb("#0067C0"),
            base: argb("#0078D4"),
            light1: argb("#0091F8"),
            light2: argb("#4CC2FF"),
            light3: argb("#99EBFF"),
        }
    }

    /// Approximate the Windows ramp for an arbitrary base accent.
    ///
    /// Windows' generator is not published; this reproduces its *shape* —
    /// three progressively darker and three progressively lighter shades,
    /// with the same spacing the default `#0078D4` ramp exhibits — so a
    /// custom accent lands in the same tonal neighbourhood. Use
    /// [`Self::windows_default`] when the base *is* `#0078D4`; it returns
    /// the measured values rather than the approximation.
    pub fn from_base(base: Color) -> Self {
        Self {
            dark3: base.darken(0.62),
            dark2: base.darken(0.42),
            dark1: base.darken(0.15),
            base,
            light1: base.lighten(0.12),
            light2: base.lighten(0.42),
            light3: base.lighten(0.68),
        }
    }
}

/// Which edge of a raised control carries its emphasised stroke.
///
/// Fluent's `ControlElevationBorderBrush` is a single gradient anchored to
/// a fixed 3 dp band at the top of the control, painting
/// `ControlStrokeColorSecondary` (the heavier stroke) inside that band and
/// `ControlStrokeColorDefault` below it. The **light** dictionary flips the
/// gradient (`ScaleTransform ScaleY="-1"`), so the heavier stroke lands at
/// the bottom; the **dark** dictionary does not, so it stays at the top.
///
/// The result is a coherent lighting model rather than a decoration: a
/// light-theme control casts a darker shadow along its bottom edge, a
/// dark-theme control catches a lighter highlight along its top edge.
/// `AccentControlElevationBorderBrush` is flipped in *both* dictionaries,
/// so an accent-filled control always carries its emphasis at the bottom.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FluentEdgeSide {
    Top,
    Bottom,
}

/// The WinUI 3 theme-resource palette for one appearance.
///
/// Installed on the theme via `theme.with_extension(...)` and read back
/// with `theme.extension::<FluentPalette>()`. Field names mirror the WinUI
/// resource keys with the `Color` suffix dropped and `snake_case` applied
/// (`ControlStrokeColorSecondary` → `control_stroke_secondary`).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct FluentPalette {
    // ── Text ──
    pub text_primary: Color,
    pub text_secondary: Color,
    pub text_tertiary: Color,
    pub text_disabled: Color,
    pub text_on_accent_primary: Color,
    pub text_on_accent_secondary: Color,
    pub text_on_accent_disabled: Color,
    pub text_on_accent_selected: Color,

    // ── Accent ──
    /// The generated accent ramp this palette was built from.
    pub accent_ramp: FluentAccentRamp,
    pub accent_fill_default: Color,
    pub accent_fill_secondary: Color,
    pub accent_fill_tertiary: Color,
    pub accent_fill_disabled: Color,
    pub accent_text_primary: Color,
    pub accent_text_secondary: Color,
    pub accent_text_tertiary: Color,
    pub accent_text_disabled: Color,

    // ── Control fills ──
    pub control_fill_default: Color,
    pub control_fill_secondary: Color,
    pub control_fill_tertiary: Color,
    pub control_fill_disabled: Color,
    pub control_fill_transparent: Color,
    pub control_fill_input_active: Color,
    pub control_alt_fill_transparent: Color,
    pub control_alt_fill_secondary: Color,
    pub control_alt_fill_tertiary: Color,
    pub control_alt_fill_quarternary: Color,
    pub control_alt_fill_disabled: Color,
    pub control_strong_fill_default: Color,
    pub control_strong_fill_disabled: Color,
    pub control_solid_fill_default: Color,

    // ── Subtle fills ──
    pub subtle_fill_transparent: Color,
    pub subtle_fill_secondary: Color,
    pub subtle_fill_tertiary: Color,
    pub subtle_fill_disabled: Color,

    // ── Backgrounds ──
    pub solid_background_base: Color,
    pub solid_background_secondary: Color,
    pub solid_background_tertiary: Color,
    pub solid_background_quarternary: Color,
    pub solid_background_base_alt: Color,
    pub layer_fill_default: Color,
    pub layer_fill_alt: Color,
    pub card_background_default: Color,
    pub card_background_secondary: Color,
    pub card_stroke_default: Color,
    pub card_stroke_default_solid: Color,

    // ── Strokes ──
    pub control_stroke_default: Color,
    pub control_stroke_secondary: Color,
    pub control_stroke_on_accent_default: Color,
    pub control_stroke_on_accent_secondary: Color,
    pub control_stroke_on_accent_tertiary: Color,
    pub control_stroke_on_accent_disabled: Color,
    pub control_strong_stroke_default: Color,
    pub control_strong_stroke_disabled: Color,
    pub divider_stroke_default: Color,
    pub surface_stroke_default: Color,
    pub surface_stroke_flyout: Color,
    pub focus_stroke_outer: Color,
    pub focus_stroke_inner: Color,

    // ── System (status) fills ──
    pub system_fill_success: Color,
    pub system_fill_success_background: Color,
    pub system_fill_caution: Color,
    pub system_fill_caution_background: Color,
    pub system_fill_critical: Color,
    pub system_fill_critical_background: Color,
    pub system_fill_attention: Color,
    pub system_fill_attention_background: Color,
    pub system_fill_neutral: Color,
    pub system_fill_neutral_background: Color,

    // ── Misc ──
    /// Dialog / content-dialog dimming scrim (`SmokeFillColorDefault`).
    pub smoke_fill_default: Color,

    /// Which edge a *neutral* raised control emphasises — see
    /// [`FluentEdgeSide`]. `Bottom` in light, `Top` in dark.
    pub elevation_edge: FluentEdgeSide,
}

impl FluentPalette {
    /// The **light** WinUI theme dictionary, with the accent family resolved
    /// against the Windows default accent `#0078D4`.
    pub fn light() -> Self {
        Self::light_with_accent(FluentAccentRamp::windows_default())
    }

    /// The **dark** WinUI theme dictionary, with the accent family resolved
    /// against the Windows default accent `#0078D4`.
    pub fn dark() -> Self {
        Self::dark_with_accent(FluentAccentRamp::windows_default())
    }

    /// The light dictionary with a caller-supplied accent ramp substituted
    /// for the `{ThemeResource SystemAccentColor*}` bindings — the same
    /// substitution Windows performs when the user picks an accent colour.
    ///
    /// Light theme binds `AccentFillColorDefault` to **`dark1`** (a darkened
    /// accent, so `TextOnAccentFillColorPrimary` white clears contrast on
    /// it) and the accent *text* roles to `dark2` / `dark3`.
    pub fn light_with_accent(ramp: FluentAccentRamp) -> Self {
        Self {
            text_primary: argb("#E4000000"),
            text_secondary: argb("#9E000000"),
            text_tertiary: argb("#72000000"),
            text_disabled: argb("#5C000000"),
            text_on_accent_primary: argb("#FFFFFFFF"),
            text_on_accent_secondary: argb("#B3FFFFFF"),
            text_on_accent_disabled: argb("#FFFFFFFF"),
            text_on_accent_selected: argb("#FFFFFFFF"),

            accent_ramp: ramp,
            accent_fill_default: ramp.dark1,
            // WinUI expresses Secondary / Tertiary as the *same* brush at
            // 90 % / 80 % opacity rather than as separate colours; the
            // control sits on an opaque surface, so the flattened result is
            // what actually reaches the screen.
            accent_fill_secondary: ramp.dark1.with_alpha(0.9),
            accent_fill_tertiary: ramp.dark1.with_alpha(0.8),
            accent_fill_disabled: argb("#37000000"),
            accent_text_primary: ramp.dark2,
            accent_text_secondary: ramp.dark3,
            accent_text_tertiary: ramp.dark1,
            accent_text_disabled: argb("#5C000000"),

            control_fill_default: argb("#B3FFFFFF"),
            control_fill_secondary: argb("#80F9F9F9"),
            control_fill_tertiary: argb("#4DF9F9F9"),
            control_fill_disabled: argb("#4DF9F9F9"),
            control_fill_transparent: argb("#00FFFFFF"),
            control_fill_input_active: argb("#FFFFFFFF"),
            control_alt_fill_transparent: argb("#00FFFFFF"),
            control_alt_fill_secondary: argb("#06000000"),
            control_alt_fill_tertiary: argb("#0F000000"),
            control_alt_fill_quarternary: argb("#18000000"),
            control_alt_fill_disabled: argb("#00FFFFFF"),
            control_strong_fill_default: argb("#72000000"),
            control_strong_fill_disabled: argb("#51000000"),
            control_solid_fill_default: argb("#FFFFFFFF"),

            subtle_fill_transparent: argb("#00FFFFFF"),
            subtle_fill_secondary: argb("#09000000"),
            subtle_fill_tertiary: argb("#06000000"),
            subtle_fill_disabled: argb("#00FFFFFF"),

            solid_background_base: argb("#F3F3F3"),
            solid_background_secondary: argb("#EEEEEE"),
            solid_background_tertiary: argb("#F9F9F9"),
            solid_background_quarternary: argb("#FFFFFF"),
            solid_background_base_alt: argb("#DADADA"),
            layer_fill_default: argb("#80FFFFFF"),
            layer_fill_alt: argb("#FFFFFFFF"),
            card_background_default: argb("#B3FFFFFF"),
            card_background_secondary: argb("#80F6F6F6"),
            card_stroke_default: argb("#0F000000"),
            card_stroke_default_solid: argb("#EBEBEB"),

            control_stroke_default: argb("#0F000000"),
            control_stroke_secondary: argb("#29000000"),
            control_stroke_on_accent_default: argb("#14FFFFFF"),
            control_stroke_on_accent_secondary: argb("#66000000"),
            control_stroke_on_accent_tertiary: argb("#37000000"),
            control_stroke_on_accent_disabled: argb("#0F000000"),
            control_strong_stroke_default: argb("#72000000"),
            control_strong_stroke_disabled: argb("#37000000"),
            divider_stroke_default: argb("#0F000000"),
            surface_stroke_default: argb("#66757575"),
            surface_stroke_flyout: argb("#0F000000"),
            focus_stroke_outer: argb("#E4000000"),
            focus_stroke_inner: argb("#B3FFFFFF"),

            system_fill_success: argb("#0F7B0F"),
            system_fill_success_background: argb("#DFF6DD"),
            system_fill_caution: argb("#9D5D00"),
            system_fill_caution_background: argb("#FFF4CE"),
            system_fill_critical: argb("#C42B1C"),
            system_fill_critical_background: argb("#FDE7E9"),
            // `SystemFillColorAttention` binds straight to the *base*
            // accent in both appearances — no Light/Dark shift.
            system_fill_attention: ramp.base,
            system_fill_attention_background: argb("#80F6F6F6"),
            system_fill_neutral: argb("#72000000"),
            system_fill_neutral_background: argb("#06000000"),

            smoke_fill_default: argb("#4D000000"),
            // The light dictionary flips `ControlElevationBorderBrush`, so
            // the heavier stroke sits along the bottom — a cast shadow.
            elevation_edge: FluentEdgeSide::Bottom,
        }
    }

    /// The dark dictionary with a caller-supplied accent ramp substituted.
    ///
    /// Dark theme binds `AccentFillColorDefault` to **`light2`** (a
    /// lightened accent, so `TextOnAccentFillColorPrimary` *black* clears
    /// contrast on it) and the accent *text* roles to `light3` / `light2`.
    pub fn dark_with_accent(ramp: FluentAccentRamp) -> Self {
        Self {
            text_primary: argb("#FFFFFFFF"),
            text_secondary: argb("#C5FFFFFF"),
            text_tertiary: argb("#87FFFFFF"),
            text_disabled: argb("#5DFFFFFF"),
            text_on_accent_primary: argb("#FF000000"),
            text_on_accent_secondary: argb("#80000000"),
            // Not a typo: a *disabled* accent surface is no longer accent
            // coloured (it is `#28FFFFFF`), so its label reverts to white.
            text_on_accent_disabled: argb("#87FFFFFF"),
            text_on_accent_selected: argb("#FFFFFFFF"),

            accent_ramp: ramp,
            accent_fill_default: ramp.light2,
            accent_fill_secondary: ramp.light2.with_alpha(0.9),
            accent_fill_tertiary: ramp.light2.with_alpha(0.8),
            accent_fill_disabled: argb("#28FFFFFF"),
            accent_text_primary: ramp.light3,
            accent_text_secondary: ramp.light3,
            accent_text_tertiary: ramp.light2,
            accent_text_disabled: argb("#5DFFFFFF"),

            control_fill_default: argb("#0FFFFFFF"),
            control_fill_secondary: argb("#15FFFFFF"),
            control_fill_tertiary: argb("#08FFFFFF"),
            control_fill_disabled: argb("#0BFFFFFF"),
            control_fill_transparent: argb("#00FFFFFF"),
            control_fill_input_active: argb("#B31E1E1E"),
            control_alt_fill_transparent: argb("#00FFFFFF"),
            control_alt_fill_secondary: argb("#19000000"),
            control_alt_fill_tertiary: argb("#0BFFFFFF"),
            control_alt_fill_quarternary: argb("#12FFFFFF"),
            control_alt_fill_disabled: argb("#00FFFFFF"),
            control_strong_fill_default: argb("#8BFFFFFF"),
            control_strong_fill_disabled: argb("#3FFFFFFF"),
            control_solid_fill_default: argb("#FF454545"),

            subtle_fill_transparent: argb("#00FFFFFF"),
            subtle_fill_secondary: argb("#0FFFFFFF"),
            subtle_fill_tertiary: argb("#0AFFFFFF"),
            subtle_fill_disabled: argb("#00FFFFFF"),

            solid_background_base: argb("#FF202020"),
            solid_background_secondary: argb("#FF1C1C1C"),
            solid_background_tertiary: argb("#FF282828"),
            solid_background_quarternary: argb("#FF2C2C2C"),
            solid_background_base_alt: argb("#FF0A0A0A"),
            layer_fill_default: argb("#4C3A3A3A"),
            layer_fill_alt: argb("#0DFFFFFF"),
            card_background_default: argb("#0DFFFFFF"),
            card_background_secondary: argb("#08FFFFFF"),
            card_stroke_default: argb("#19000000"),
            card_stroke_default_solid: argb("#FF1C1C1C"),

            control_stroke_default: argb("#12FFFFFF"),
            control_stroke_secondary: argb("#18FFFFFF"),
            control_stroke_on_accent_default: argb("#14FFFFFF"),
            control_stroke_on_accent_secondary: argb("#23000000"),
            control_stroke_on_accent_tertiary: argb("#37000000"),
            control_stroke_on_accent_disabled: argb("#33000000"),
            control_strong_stroke_default: argb("#8BFFFFFF"),
            control_strong_stroke_disabled: argb("#28FFFFFF"),
            divider_stroke_default: argb("#15FFFFFF"),
            surface_stroke_default: argb("#66757575"),
            surface_stroke_flyout: argb("#33000000"),
            // The two-tone ring flips with the appearance: the *outer*,
            // thicker ring is always the high-contrast one.
            focus_stroke_outer: argb("#FFFFFFFF"),
            focus_stroke_inner: argb("#B3000000"),

            system_fill_success: argb("#FF6CCB5F"),
            system_fill_success_background: argb("#FF393D1B"),
            system_fill_caution: argb("#FFFCE100"),
            system_fill_caution_background: argb("#FF433519"),
            system_fill_critical: argb("#FFFF99A4"),
            system_fill_critical_background: argb("#FF442726"),
            system_fill_attention: ramp.base,
            system_fill_attention_background: argb("#08FFFFFF"),
            system_fill_neutral: argb("#8BFFFFFF"),
            system_fill_neutral_background: argb("#08FFFFFF"),

            smoke_fill_default: argb("#4D000000"),
            // The dark dictionary does NOT flip the gradient, so the
            // heavier stroke stays at the top — a catch-light.
            elevation_edge: FluentEdgeSide::Top,
        }
    }

    /// The opaque colour a control fill resolves to on the page
    /// background: the translucent `ControlFillColorDefault` composited
    /// over `SolidBackgroundFillColorBase`. Used wherever Teksilo needs a
    /// flat value — a field surface the caret and selection are measured
    /// against, a button fill.
    pub fn control_fill_default_solid(&self) -> Color {
        over(self.control_fill_default, self.solid_background_base)
    }

    /// The opaque colour `ControlFillColorSecondary` (the hover fill)
    /// resolves to on the page background.
    pub fn control_fill_secondary_solid(&self) -> Color {
        over(self.control_fill_secondary, self.solid_background_base)
    }

    /// The opaque colour `ControlFillColorTertiary` (the pressed fill)
    /// resolves to on the page background.
    pub fn control_fill_tertiary_solid(&self) -> Color {
        over(self.control_fill_tertiary, self.solid_background_base)
    }

    /// The opaque colour `ControlFillColorDisabled` resolves to on the
    /// page background.
    pub fn control_fill_disabled_solid(&self) -> Color {
        over(self.control_fill_disabled, self.solid_background_base)
    }

    /// The opaque surface a layered container (a settings-card region, a
    /// grouped list) resolves to — `LayerFillColorDefault` over
    /// `SolidBackgroundFillColorBase`.
    pub fn layer_base(&self) -> Color {
        over(self.layer_fill_default, self.solid_background_base)
    }

    /// The opaque surface a `Card` resolves to on the page background.
    pub fn card_background_solid(&self) -> Color {
        over(self.card_background_default, self.solid_background_base)
    }

    /// The emphasised stroke a **neutral** raised control draws, and which
    /// edge it draws it on. See [`FluentEdgeSide`].
    pub fn control_elevation_edge(&self) -> (FluentEdgeSide, Color) {
        (self.elevation_edge, self.control_stroke_secondary)
    }

    /// The emphasised stroke an **accent-filled** control draws. Always the
    /// bottom edge — `AccentControlElevationBorderBrush` is flipped in both
    /// dictionaries.
    pub fn accent_elevation_edge(&self) -> (FluentEdgeSide, Color) {
        (
            FluentEdgeSide::Bottom,
            self.control_stroke_on_accent_secondary,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn argb_decodes_alpha_first() {
        // WinUI writes #AARRGGBB; the red channel must land in `r`, not `a`.
        let c = argb("#80FF0000");
        assert!((c.r() - 1.0).abs() < 1e-6);
        assert!(c.g().abs() < 1e-6);
        assert!(c.b().abs() < 1e-6);
        assert!((c.a() - 128.0 / 255.0).abs() < 1e-6);
    }

    #[test]
    fn argb_accepts_opaque_six_digit_form() {
        let c = argb("#F3F3F3");
        assert!((c.a() - 1.0).abs() < 1e-6);
        assert!((c.r() - c.b()).abs() < 1e-6);
    }

    #[test]
    fn over_composites_source_over() {
        // 50 % white over black is mid-grey and fully opaque.
        let c = over(Color::new(1.0, 1.0, 1.0, 0.5), Color::BLACK);
        assert!((c.r() - 0.5).abs() < 1e-6);
        assert!((c.a() - 1.0).abs() < 1e-6);
    }

    #[test]
    fn light_and_dark_accent_fills_come_from_opposite_ramp_ends() {
        let ramp = FluentAccentRamp::windows_default();
        assert_eq!(FluentPalette::light().accent_fill_default, ramp.dark1);
        assert_eq!(FluentPalette::dark().accent_fill_default, ramp.light2);
    }

    #[test]
    fn on_accent_text_clears_contrast_in_both_appearances() {
        // The whole point of the asymmetric ramp: white-on-dark1 (light
        // theme) and black-on-light2 (dark theme) must both be legible.
        let l = FluentPalette::light();
        let d = FluentPalette::dark();
        assert!(
            l.accent_fill_default
                .contrast_ratio(l.text_on_accent_primary)
                >= 4.5
        );
        assert!(
            d.accent_fill_default
                .contrast_ratio(d.text_on_accent_primary)
                >= 4.5
        );
    }

    #[test]
    fn custom_accent_ramp_is_substituted_everywhere() {
        let ramp = FluentAccentRamp::from_base(Color::from_hex("#B146C2"));
        let p = FluentPalette::light_with_accent(ramp);
        assert_eq!(p.accent_fill_default, ramp.dark1);
        assert_eq!(p.accent_text_primary, ramp.dark2);
        assert_eq!(p.system_fill_attention, ramp.base);
        assert_ne!(
            p.accent_fill_default,
            FluentPalette::light().accent_fill_default
        );
    }

    #[test]
    fn ramp_from_base_is_monotonic_in_luminance() {
        let r = FluentAccentRamp::from_base(Color::from_hex("#0078D4"));
        let l = |c: Color| c.relative_luminance();
        assert!(l(r.dark3) < l(r.dark2));
        assert!(l(r.dark2) < l(r.dark1));
        assert!(l(r.dark1) < l(r.base));
        assert!(l(r.base) < l(r.light1));
        assert!(l(r.light1) < l(r.light2));
        assert!(l(r.light2) < l(r.light3));
    }

    #[test]
    fn layer_base_is_opaque() {
        for p in [FluentPalette::light(), FluentPalette::dark()] {
            assert!((p.layer_base().a() - 1.0).abs() < 1e-6);
            assert!((p.control_fill_default_solid().a() - 1.0).abs() < 1e-6);
        }
    }
}
