# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 FernTech

[package]
name = "teksilo-fmt"
edition = "2024"
version.workspace = true
license-file.workspace = true
publish.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
teksilo-parse = { workspace = true }
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
syn = { version = "3", features = ["full", "extra-traits", "visit"] }
thiserror = { workspace = true }
