# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 FernTech

[package]
name = "bastyde-core"
edition = "2024"
version.workspace = true
license-file.workspace = true
publish.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bastyde-tokens = { workspace = true }
bastyde-canvas = { workspace = true }
accesskit = { workspace = true }
slotmap = "1"
serde = { workspace = true }
thiserror = { workspace = true }
raw-window-handle = "0.6"

[dev-dependencies]
accesskit_consumer = { workspace = true }
