# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 FernTech

[package]
name = "widget-catalog"
edition = "2024"
version.workspace = true
license-file.workspace = true
authors.workspace = true
publish = false

[dependencies]
bastyde = { workspace = true, features = [
    "automation",
    "system-emoji",
    "telemetry",
    "theme-material3",
] }
bastyde-charts = { workspace = true }
bastyde-scene = { workspace = true }
bastyde-telemetry = { workspace = true }
jiff = { workspace = true }

[dev-dependencies]
bastyde-render = { workspace = true }
wgpu = { workspace = true }
pollster = { workspace = true }
