[package]
name = "widget-catalog"
edition = "2024"
version.workspace = true
license-file.workspace = true
authors.workspace = true
publish = false

[dependencies]
bastyde = { workspace = true, features = ["system-emoji", "telemetry"] }
bastyde-charts = { workspace = true }
bastyde-scene = { workspace = true }
bastyde-telemetry = { workspace = true }
jiff = { workspace = true }

[dev-dependencies]
bastyde-render = { workspace = true }
wgpu = { workspace = true }
pollster = "0.4"
