[package]
name = "widget-catalog"
edition = "2024"
version.workspace = true
license-file.workspace = true
authors.workspace = true
publish = false

[dependencies]
bastyde = { workspace = true, features = ["rich-text", "system-emoji"] }
jiff = { workspace = true }

[dev-dependencies]
bastyde-render = { workspace = true }
wgpu = { workspace = true }
pollster = "0.4"
