[package]
name = "fern-render"
edition = "2024"
version.workspace = true
license-file.workspace = true
publish.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
fern-canvas = { workspace = true }
wgpu = { workspace = true }
tiny-skia = { workspace = true }
bytemuck = { version = "1", features = ["derive"] }

[dev-dependencies]
fern-tokens = { workspace = true }
pollster = "0.4"
