[package]
name = "fern-i18n"
edition = "2024"
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
fern-core = { workspace = true }
fern-i18n-macros = { workspace = true }
fluent-bundle = { workspace = true }
fluent-syntax = { workspace = true }
unic-langid = { workspace = true }
sys-locale = { workspace = true }
notify = { workspace = true }

[dev-dependencies]
trybuild = "1"
