# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 FernTech

[package]
name = "file-dialogs"
edition = "2024"
version.workspace = true
license-file.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "file-dialogs"
path = "src/main.rs"

[dependencies]
teksilo = { workspace = true, features = [
    "automation","file-dialog"] }
