# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 FernTech

[package]
name = "telemetry-codegen"
edition = "2024"
version.workspace = true
license-file.workspace = true
publish = false
authors.workspace = true
repository.workspace = true

[dependencies]
teksilo-telemetry = { workspace = true }
teksilo-telemetry-codegen = { workspace = true }
