[package]
name = "fern-preview-ui"
edition = "2024"
version.workspace = true
license-file.workspace = true
publish.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
fern-core = { workspace = true }
fern-tokens = { workspace = true }
fern-canvas = { workspace = true }
fern-data = { workspace = true }
fern-app = { workspace = true }
fern-i18n = { workspace = true }
fern-widgets = { workspace = true, features = ["rich-text"] }
fern-preview = { workspace = true }
fern-render = { workspace = true }
fern-platform = { workspace = true }
png = { workspace = true }
wgpu = { workspace = true }
pollster = "0.4"
